repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: double-quote-string-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: detect-private-key
#  - repo: 'https://github.com/prettier/prettier'
#    rev: 3.3.0
#    hooks:
#      - id: prettier
#        args:
#          - '--in-place'
#        types:
#          - yaml
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle
        entry: ./run-checkstyle.sh
        language: script
        files: \.java$
  - repo: 'https://github.com/jumanjihouse/pre-commit-hooks'
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: script-must-have-extension
      - id: git-dirty
      - id: git-check
        exclude: \.md$
      - id: forbid-binary
        exclude: \.(jpg|jpeg|png)$
