repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-json
        - id: check-yaml
        - id: pretty-format-json
          args: ['--autofix']
        - id: double-quote-string-fixer
        - id: check-shebang-scripts-are-executable # Ensures that scripts with a shebang (#!) are executable.
        - id: check-executables-have-shebangs
        - id: detect-private-key # Detects private keys in the repository to prevent accidental commits.
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1  # or other specific tag
    hooks:
      - id: yamlfmt
  - repo: local # used for java code if exist
    hooks:
      - id: checkstyle
        name: Checkstyle
        entry: ./run-checkstyle.sh # script to call java code formatter
        language: script
        files: \.java$
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: script-must-have-extension
      - id: git-dirty
      - id: git-check
        exclude: '\.md$'  # Exclude Markdown files
      - id: forbid-binary
        exclude: '\.(jpg|jpeg|png)$' # except images
